# Generated by Django 4.1.3 on 2023-01-08 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Settings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app', models.TextField(max_length=20)),
                ('key', models.TextField(max_length=50)),
                ('value', models.TextField(max_length=50)),
                ('readOnly', models.BooleanField(default=False)),
                ('visible', models.BooleanField(default=False)),
            ],
        ),
    ]
