# Generated by Django 4.1.3 on 2023-03-12 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='settings',
            name='app',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='settings',
            name='key',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='settings',
            name='value',
            field=models.CharField(max_length=50),
        ),
    ]
