# Generated by Django 4.1.3 on 2023-01-08 20:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0002_settings_visible'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='settings',
            unique_together={('app', 'key')},
        ),
    ]
