# Generated by Django 4.1.3 on 2023-03-12 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0004_alter_settings_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='settings',
            name='value',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
