# Generated by Django 4.1.3 on 2022-12-18 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Settings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_created=True)),
                ('access_token', models.TextField(max_length=100)),
                ('expires', models.BigIntegerField()),
                ('refresh_token', models.TextField(max_length=200)),
                ('scope', models.TextField(max_length=200)),
                ('token_type', models.TextField(max_length=50)),
            ],
        ),
    ]
