# Generated by Django 4.1.3 on 2022-12-26 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StreamTimer', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='streamtimer',
            name='colorWheel',
        ),
        migrations.RemoveField(
            model_name='streamtimer',
            name='endtime',
        ),
        migrations.AddField(
            model_name='streamtimer',
            name='key',
            field=models.TextField(default='ss', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='streamtimer',
            name='value',
            field=models.TextField(default='ssss', max_length=20),
            preserve_default=False,
        ),
    ]
