# Generated by Django 4.1.3 on 2023-01-07 15:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('StreamTimer', '0002_remove_streamtimer_colorwheel_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='StreamTimer',
        ),
    ]
