# Generated by Django 4.1.3 on 2023-01-07 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('StreamTimer', '0003_delete_streamtimer'),
    ]

    operations = [
        migrations.CreateModel(
            name='StreamTimer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.TextField(max_length=20)),
                ('value', models.TextField(max_length=20)),
            ],
        ),
    ]
