# Generated by Django 4.1.3 on 2022-11-20 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Command',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('command', models.TextField(max_length=200)),
                ('actionRequired', models.BooleanField(default=False)),
                ('builtIn', models.BooleanField(default=False)),
                ('cooldown', models.DurationField()),
                ('data', models.TextField(max_length=200)),
                ('roleRequired', models.TextField()),
            ],
        ),
    ]
