# Generated by Django 4.1.6 on 2023-03-25 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Commands', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='command',
            name='cooldown',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='command',
            name='lastUsed',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='command',
            name='usage',
            field=models.TextField(max_length=200),
        ),
    ]
