# Generated by Django 4.1.3 on 2022-11-20 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Commands', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='command',
            name='roleRequired',
            field=models.TextField(max_length=200),
        ),
    ]
