# Generated by Django 4.1.3 on 2022-12-26 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Commands', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='command',
            name='lastUsed',
            field=models.TextField(default='d', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='command',
            name='usage',
            field=models.TextField(default='d'),
            preserve_default=False,
        ),
    ]
