# Generated by Django 4.1.3 on 2022-11-20 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Commands', '0002_alter_command_rolerequired'),
    ]

    operations = [
        migrations.AlterField(
            model_name='command',
            name='cooldown',
            field=models.TextField(max_length=200),
        ),
    ]
