# Generated by Django 4.1.3 on 2023-01-07 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0002_remove_user_time_in_chat_user_role_user_room_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Roles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.TextField(max_length=20)),
                ('shortHand', models.TextField(max_length=4)),
            ],
        ),
    ]
