# Generated by Django 4.1.3 on 2023-01-08 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0004_alter_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.TextField(choices=[(1, 'Admin')], default='d'),
        ),
    ]
